// GENRES------------------------------------------------------
export const FETCH_GENRES = 'FETCH_GENRES'
export const FETCH_GENRES_START = 'FETCH_GENRES_START'
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS'
export const FETCH_GENRES_FAIL = 'FETCH_GENRES_FAIL'

export const CREATE_GENRE = 'CREATE_GENRE'
export const CREATE_GENRE_START = 'CREATE_GENRE_START'
export const CREATE_GENRE_SUCCESS = 'CREATE_GENRE_SUCCESS'
export const CREATE_GENRE_FAIL = 'CREATE_GENRE_FAIL'

export const DELETE_GENRE = 'DELETE_GENRE'
export const DELETE_GENRE_START = 'DELETE_GENRE_START'
export const DELETE_GENRE_SUCCESS = 'DELETE_GENRE_SUCCESS'
export const DELETE_GENRE_FAIL = 'DELETE_GENRE_FAIL'

export const UPDATE_GENRE = 'UPDATE_GENRE'
export const UPDATE_GENRE_START = 'UPDATE_GENRE_START'
export const UPDATE_GENRE_SUCCESS = 'UPDATE_GENRE_SUCCESS'
export const UPDATE_GENRE_FAIL = 'UPDATE_GENRE_FAIL'


